# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsCostReport < Formula
  desc ""
  homepage "https://github.com/stangirard/aws-cost-report"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/StanGirard/aws-cost-report/releases/download/0.0.4/aws-cost-report_0.0.4_Darwin_arm64.tar.gz"
      sha256 "c3187ef409147329a5d15c4e7fb9d870901324f1955db02ee4fc0a1a35fea119"

      def install
        bin.install "aws-cost-report"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/StanGirard/aws-cost-report/releases/download/0.0.4/aws-cost-report_0.0.4_Darwin_x86_64.tar.gz"
      sha256 "ba8344440fa20748323caee03866116456e19035f5f78a269675b20cacedcde9"

      def install
        bin.install "aws-cost-report"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/StanGirard/aws-cost-report/releases/download/0.0.4/aws-cost-report_0.0.4_Linux_x86_64.tar.gz"
      sha256 "0a95a1f49495fd79bcbbe1923c6372ba589ea151f50f7068e0511b8d818d12bd"

      def install
        bin.install "aws-cost-report"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/StanGirard/aws-cost-report/releases/download/0.0.4/aws-cost-report_0.0.4_Linux_arm64.tar.gz"
      sha256 "bdb08fa68f67e0faedbabdfda0cbd5956ed11c59380653240d6b664031508edc"

      def install
        bin.install "aws-cost-report"
      end
    end
  end
end
